"""Tests for src/core/bridge_log.py — mapping bridge /logs events to EventModel."""
from __future__ import annotations

import pytest

from src.core.bridge_log import map_log_event, map_log_events
from src.core.schemas import EventCategory, EventLevel


def _log(**kw):
    base = {
        "id": "log_abc", "created_at": "2026-05-29T10:00:00+00:00", "source": "llm",
        "direction": "input", "mode": "chat", "request_id": "req_1",
        "session_id": "sess_1", "run_id": "run_1", "status_code": 200, "ok": True,
        "payload": {"text": "hello"},
    }
    base.update(kw)
    return base


def test_llm_input_maps_to_llm_request():
    evt = map_log_event(_log(direction="input"))
    assert evt.category == EventCategory.LLM
    assert evt.type == "llm.request"
    assert evt.level == EventLevel.INFO
    assert evt.id == "log_abc"
    assert evt.request_id == "req_1" and evt.session_id == "sess_1" and evt.run_id == "run_1"
    assert evt.timestamp.year == 2026
    assert "request" in evt.summary.lower()


def test_llm_output_maps_to_llm_response():
    evt = map_log_event(_log(direction="output"))
    assert evt.type == "llm.response"
    assert "response" in evt.summary.lower()


def test_ok_false_is_error_level():
    evt = map_log_event(_log(ok=False))
    assert evt.level == EventLevel.ERROR


def test_status_4xx_is_error_level():
    evt = map_log_event(_log(ok=None, status_code=500))
    assert evt.level == EventLevel.ERROR


def test_payload_preserved_in_details():
    evt = map_log_event(_log(payload={"text": "hi", "tokens": 12}))
    assert evt.details["payload"] == {"text": "hi", "tokens": 12}
    # ids are promoted to top-level fields, not duplicated in details
    assert "request_id" not in evt.details


def test_unknown_source_falls_back_to_system_category():
    evt = map_log_event(_log(source="weird", direction=""))
    assert evt.category == EventCategory.SYSTEM
    assert evt.type == "system.event"


def test_missing_id_gets_autogenerated():
    raw = _log(); del raw["id"]
    evt = map_log_event(raw)
    assert evt.id.startswith("evt_")


def test_non_dict_raises():
    with pytest.raises(ValueError):
        map_log_event(["not", "a", "dict"])


def test_map_log_events_skips_malformed():
    events = map_log_events([_log(id="log_1"), "garbage", _log(id="log_2", direction="output")])
    assert [e.id for e in events] == ["log_1", "log_2"]
    assert events[1].type == "llm.response"
